- name: deb-utils
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - git
      - ftp
      - jq
      - telnet
      - netcat
      - socat
      - rdesktop
      - tmux
      - vim
      - golang-go
      - python
      - python-pip
      - python3
      - python3-pip
      - nmap
      - docker.io
  tasks:
    - name: install deb-utils packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
  tags:
    - deb-utils

- name: deb-sec
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - nbtscan
      - samba-common-bin
      - smbclient
      - polenum
      - ldap-utils
      - samba
      - cifs-utils
      - python-scapy
      - python3-scapy
      - scanssh
      - zenmap
      - sqlmap
      - dnsrecon
      - ncrack
      - onesixtyone
      - cewl
      - john
      - hashcat
      - hydra
      - recon-ng
      - aircrack-ng
      - airgraph-ng
      - kismet
      - wireshark
      - tshark
      - hunt
      - mdbtools
      - pst-utils
      - p7zip-full
      - libimage-exiftool-perl
      - steghide
      - beef
      - gobuster
  tasks:
    - name: install deb-sec packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
  tags:
    - deb-sec

- name: pip-sec
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - impacket
      - dirhunt
      - crackmapexec
  tasks:
    - name: install pip-sec packages
      pip:
        name: "{{ item }}"
        state: present
        extra_args: --upgrade
      loop: "{{ packages }}"
  tags:
    - pip-sec

- name: pip3-sec
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - pshtt
  tasks:
    - name: install pip3-sec packages
      pip:
        name: "{{ item }}"
        executable: pip3
        state: present
        extra_args: --upgrade
      loop: "{{ packages }}"
  tags:
    - pip3-sec

- name: wordlists
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: create wordlist directory
      file:
        path: /usr/share/wordlists/dirbuster
        state: directory
    - name: download wordlists
      get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/apache-user-enum-1.0.txt',
            dest: /usr/share/wordlists/dirbuster/apache-user-enum-1.0.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/apache-user-enum-2.0.txt',
            dest: /usr/share/wordlists/dirbuster/apache-user-enum-2.0.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-1.0.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-1.0.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-2.3-big.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-2.3-big.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-2.3-medium.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-2.3-small.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-2.3-small.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-lowercase-2.3-big.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-2.3-big.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-lowercase-2.3-medium.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-lowercase-2.3-medium.txt }
        - { src: 'https://raw.githubusercontent.com/daviddias/node-dirbuster/master/lists/directory-list-lowercase-2.3-small.txt',
            dest: /usr/share/wordlists/dirbuster/directory-list-lowercase-2.3-small.txt }
        - { src: 'https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt',
            dest: /usr/share/wordlists/rockyou.txt }
        - { src: 'https://www.wirelessvillage.ninja/docs/spy_vs_spy.words',
            dest: /usr/share/wordlists/spy_vs_spy.words }
  tags:
    - wordlists

